repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        files: \.(cpp|hpp|cc|h|c|ino)$
        args: ["-style=Google"]

  - repo: https://github.com/pre-commit/mirrors-markdownlint-cli2
    rev: v0.9.2
    hooks:
      - id: markdownlint-cli2
        files: \.(md|markdown)$
