name: Build Firmware

on:
  push:
    tags:
      - 'v*'  # Triggert bei Tag-Push (z.B. v1.0.0)
  workflow_dispatch:  # Manueller Trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Build Environment
      run: |
        # Installiere benötigte Tools (z.B. für Arduino, ESP32, etc.)
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Build Firmware
      run: |
        # Deine Build-Befehle hier
        make firmware
        # oder für Arduino: arduino-cli compile
        # oder für ESP32: idf.py build
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          firmware.bin
          firmware.hex
          # Weitere Firmware-Dateien

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install Board Package
      run: arduino-cli core install esp32:esp32
      
    - name: Compile Sketch
      run: arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir build/

  
